// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sittellalab/pigo/pkg/icons"
import "fmt"

type ThemeToggleIcon int

const (
	ClassicToggle ThemeToggleIcon = iota
	InnerMoonToggle
	ExpandToggle
	WithinToggle
	AroundToggle
	DarkSideToggle
	HorizonToggle
	EclipseToggle
	LightbulbToggle
	DarkInnerToggle
	HalfSunToggle
	SimpleToggle
)

type ThemeToggleProps struct {
	// Optional: A theme toggle icon, names found at https://toggles.dev/
	//
	// If left blank, defaults to Classic icon
	Icon ThemeToggleIcon
	// Optional: A css size, e.g., 16px, 1em, 1rem, etc
	//
	// If left blank, defaults to 1em
	Size string
}

// ThemeToggle will add an animated toggle switch that allows a user to manually toggle between light and dark mode.
// To get the best out of this, component, place the `@ui.DetectTheme()` script component in the <head> of your document.
//
// Note: This component requires JavaScript to function.
func ThemeToggle(props ThemeToggleProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<label class=\"theme-toggle\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Size != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("font-size: %s;", props.Size))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/theme_toggle.templ`, Line: 42, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("><input id=\"theme-toggle\" class=\"sr\" type=\"checkbox\" aria-label=\"Toggle light/dark mode\" onclick=\"\n\t\t\t\tif (event.target.checked) {\n\t\t\t\t\tdocument.documentElement.setAttribute(&#39;data-theme&#39;, &#39;dark&#39;);\n\t\t\t\t\tlocalStorage.setItem(&#39;theme&#39;, &#39;dark&#39;);\n\t\t\t\t} else {\n\t\t\t\t\tdocument.documentElement.setAttribute(&#39;data-theme&#39;, &#39;light&#39;);\n\t\t\t\t\tlocalStorage.setItem(&#39;theme&#39;, &#39;light&#39;);\n\t\t\t\t}\n\t\t\t\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.ThemeToggleMap[int(props.Icon)]().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

// DetectTheme when placed in the <head> of the html document will automatically detect the user theme preference and apply it
func DetectTheme() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_DetectTheme_150d`,
		Function: `function __templ_DetectTheme_150d(){// check for a cached theme preference
	let theme = localStorage.getItem('theme');

	// if no preference, derive it from preferred colour scheme
	if (theme === null) {
		theme = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? "dark" : "light";
		localStorage.setItem('theme', theme);
	}

	// set the colour theme
	document.documentElement.setAttribute('data-theme', theme);

	// toggle the check box if possible
	document.addEventListener('DOMContentLoaded', () => {
			const toggle = document.getElementById('theme-toggle');
			if (toggle !== null) toggle.checked = theme === 'dark';
			}, {once: true});
}`,
		Call:       templ.SafeScript(`__templ_DetectTheme_150d`),
		CallInline: templ.SafeScriptInline(`__templ_DetectTheme_150d`),
	}
}

var _ = templruntime.GeneratedTemplate
